# Generated by Django 5.0.4 on 2024-05-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_genre_slug_remove_product_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
